// Studybase Practice Quiz — front-end demo. Connect an AI/backend service for PDF-based quiz generation.
const questions=[
{question:'Which statement best describes supervised learning?',options:['A model learns from labelled examples','A model groups data without target labels','A system stores data without learning patterns','A model learns only through rewards and penalties'],correct:0,explanation:'Supervised learning uses labelled training examples, where the expected output is provided to the model.'},
{question:'Which task is a typical example of classification?',options:["Predicting tomorrow's temperature in degrees",'Estimating the price of a house','Labelling an email as spam or not spam','Forecasting monthly sales revenue'],correct:2,explanation:'Classification predicts a discrete category, such as spam or not spam. The other examples predict numeric values.'},
{question:'What is the main purpose of a test dataset?',options:['To fit model parameters during training','To evaluate performance on unseen examples','To replace missing values in every feature','To guarantee that a model has no bias'],correct:1,explanation:'A held-out test set estimates how well the trained model generalizes to data it did not use during fitting.'},
{question:'Which situation most strongly suggests overfitting?',options:['Low training performance and low test performance','Similar performance on training and test data','High test performance with no training data','Very high training performance but poor test performance'],correct:3,explanation:'Overfitting occurs when a model fits training-specific patterns too closely and performs poorly on unseen data.'},
{question:'Which metric is the fraction of all predictions that are correct?',options:['Recall','Accuracy','Precision','Mean absolute error'],correct:1,explanation:'Accuracy is the number of correct predictions divided by the total number of predictions. Precision and recall focus on positive-class predictions.'}
];
const $=id=>document.getElementById(id);const sidebar=$('sidebar'),menu=$('mobileMenu'),fileInput=$('pdfInput'),sourceList=$('sourceList'),toast=$('toast'),intro=$('quizIntro'),form=$('quizForm'),results=$('resultsPanel'),container=$('questionsContainer');let files=[],toastTimer;
function notify(message){toast.textContent=message;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),2800)}
function esc(value){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
menu.addEventListener('click',()=>{const open=sidebar.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Close navigation':'Open navigation')});
document.addEventListener('click',e=>{if(innerWidth<=800&&sidebar.classList.contains('open')&&!sidebar.contains(e.target)&&!e.target.closest('#mobileMenu')){sidebar.classList.remove('open');menu.setAttribute('aria-expanded','false')}});
document.querySelectorAll('.nav-link').forEach(link=>link.addEventListener('click',e=>{if(link.getAttribute('href')==='#'){e.preventDefault();notify(`${link.textContent.trim()} page link needs to be connected.`)}if(innerWidth<=800){sidebar.classList.remove('open');menu.setAttribute('aria-expanded','false')}}));
$('addSourceButton').addEventListener('click',()=>fileInput.click());
fileInput.addEventListener('change',e=>{let added=0;Array.from(e.target.files||[]).forEach(file=>{if(!/\.(pdf|txt|md|doc|docx)$/i.test(file.name)){notify(`${file.name}: unsupported file type.`);return}if(file.size>10*1024*1024){notify(`${file.name}: file exceeds the 10 MB limit.`);return}if(files.some(f=>f.name===file.name&&f.size===file.size&&f.lastModified===file.lastModified)){notify(`${file.name} is already in your library.`);return}files.push(file);added++});renderSources();if(added){$('recentMessage').textContent='Files selected locally. Connect your AI service to create source-linked study guides.';notify(`${added} file${added===1?'':'s'} added to this page's library.`)}fileInput.value=''});
function renderSources(){const count=files.length;$('sourceCount').textContent=count;$('materialCount').textContent=String(count).padStart(2,'0');$('selectedSourceText').textContent=`${count} source${count===1?'':'s'} selected`;$('passageCount').textContent=count?`${count} file${count===1?'':'s'} selected locally. Text extraction is not connected.`:'Add a file to keep your study materials together.';$('materialStatus').textContent=count?'FILES ADDED':'WAITING';$('materialBarFill').style.width=count?'35%':'0%';$('quizSourceLabel').textContent=count?`${count} local source${count===1?'':'s'} selected · sample questions remain active`:'Sample: Introduction to Machine Learning';sourceList.replaceChildren();if(!count){sourceList.innerHTML='<div class="source-empty"><span class="document-icon">▤</span><span>No sources added yet.</span></div>';return}files.forEach((file,index)=>{const row=document.createElement('div');row.className='source-item';const icon=document.createElement('span');icon.className='document-icon';icon.textContent='▤';const name=document.createElement('span');name.textContent=file.name;const remove=document.createElement('button');remove.className='remove-source';remove.type='button';remove.textContent='×';remove.setAttribute('aria-label',`Remove ${file.name}`);remove.addEventListener('click',()=>{files.splice(index,1);renderSources();notify('Source removed from this page.')});row.append(icon,name,remove);sourceList.append(row)})}
$('sourceSelector').addEventListener('click',()=>notify(files.length?`${files.length} source${files.length===1?'':'s'} selected. PDF-based quiz generation needs an AI backend.`:'No source selected. Add notes or a PDF in Your Library.'));
function renderQuestions(){container.innerHTML=questions.map((q,i)=>`<fieldset class="question-block"><legend class="question-title"><span class="question-number">QUESTION ${String(i+1).padStart(2,'0')}</span><br>${esc(q.question)}</legend><div class="option-list">${q.options.map((option,j)=>`<label class="option-label"><input type="radio" name="question-${i}" value="${j}"><span class="option-letter">${String.fromCharCode(65+j)}</span><span>${esc(option)}</span></label>`).join('')}</div></fieldset>`).join('');form.querySelectorAll('input[type="radio"]').forEach(input=>input.addEventListener('change',updateProgress));updateProgress()}
function updateProgress(){const answered=questions.filter((q,i)=>form.querySelector(`input[name="question-${i}"]:checked`)).length;$('answeredProgress').textContent=`${answered} of ${questions.length} answered`;$('questionProgress').textContent=`QUESTION SET · ${String(questions.length).padStart(2,'0')} QUESTIONS`;$('progressFill').style.width=`${answered/questions.length*100}%`;$('progressTrack').setAttribute('aria-valuemax',questions.length);$('progressTrack').setAttribute('aria-valuenow',answered)}
function openQuiz(){intro.hidden=true;results.hidden=true;form.hidden=false;form.reset();renderQuestions();$('quizCard').scrollIntoView({behavior:'smooth',block:'start'})}
function backToIntro(){form.hidden=true;results.hidden=true;intro.hidden=false;form.reset();$('progressFill').style.width='0%';$('progressTrack').setAttribute('aria-valuenow','0');$('quizCard').scrollIntoView({behavior:'smooth',block:'start'})}
form.addEventListener('submit',e=>{e.preventDefault();const answers=questions.map((q,i)=>{const selected=form.querySelector(`input[name="question-${i}"]:checked`);return selected?Number(selected.value):null});const missing=answers.filter(a=>a===null).length;if(missing&&!confirm(`You have ${missing} unanswered question(s). Submit anyway? Unanswered questions will be marked incorrect.`)){const first=answers.findIndex(a=>a===null);container.children[first]?.scrollIntoView({behavior:'smooth',block:'center'});return}const correct=answers.reduce((sum,a,i)=>sum+(a===questions[i].correct?1:0),0),incorrect=questions.length-correct,pct=Math.round(correct/questions.length*100);$('scorePercent').textContent=`${pct}%`;$('correctCount').textContent=correct;$('incorrectCount').textContent=incorrect;$('totalCount').textContent=questions.length;$('resultTitle').textContent=pct===100?'Excellent work.':pct>=60?'Good progress. Keep going.':'A useful first attempt.';$('resultMessage').textContent=`You answered ${correct} out of ${questions.length} questions correctly. Review the explanations below to strengthen your understanding.`;$('scoreRing').style.background=`conic-gradient(var(--green) ${pct}%, #e3ede1 ${pct}% 100%)`;$('scoreRing').style.border='0';$('scoreRing').style.padding='7px';$('scoreRing').style.backgroundClip='content-box';$('answerReview').innerHTML=questions.map((q,i)=>{const answer=answers[i],ok=answer===q.correct,chosen=answer===null?'Not answered':q.options[answer];return `<article class="review-item ${ok?'correct':'incorrect'}"><div class="review-top"><span class="review-label">QUESTION ${String(i+1).padStart(2,'0')}</span><span class="review-status">${ok?'✓ Correct':'× Incorrect'}</span></div><h5 class="review-question">${esc(q.question)}</h5><p class="review-answer"><strong>Your answer:</strong> ${esc(chosen)}</p>${!ok?`<p class="review-answer"><strong>Correct answer:</strong> ${esc(q.options[q.correct])}</p>`:''}<p class="review-explanation"><strong>Explanation:</strong> ${esc(q.explanation)}</p></article>`}).join('');form.hidden=true;results.hidden=false;$('quizCard').scrollIntoView({behavior:'smooth',block:'start'})});
$('startQuiz').addEventListener('click',openQuiz);$('resetQuiz').addEventListener('click',()=>{if(confirm('Clear your selected answers and start over?'))openQuiz()});$('retryQuiz').addEventListener('click',openQuiz);$('backToIntro').addEventListener('click',backToIntro);$('questionStat').textContent=String(questions.length).padStart(2,'0');renderSources();
